---
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:17"
      timezone: "America/Sao_Paulo"
    commit-message:
      prefix: "chore(deps):"
    open-pull-requests-limit: 5