# .github/workflows/release.yml
name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32  # v5.0.2
        with:
          go-version: '1.22'
      # More assembly might be required: Docker logins, GPG, etc.
      # It all depends on your needs.
      - name: Install Task
        uses: arduino/setup-task@v2 # v2.6.1
        with:
          version: 3.24.0
      - name: Run Task install ui deps
        run: task install_ui_deps
      - name: Run Task build_assets
        run: task build_assets
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6 # v6.0.0
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
